// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateObjective(arg1) {
  return window['go']['main']['App']['CreateObjective'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteObjective(arg1) {
  return window['go']['main']['App']['DeleteObjective'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function FetchGoal(arg1) {
  return window['go']['main']['App']['FetchGoal'](arg1);
}

export function FetchGoals() {
  return window['go']['main']['App']['FetchGoals']();
}

export function FetchNote(arg1) {
  return window['go']['main']['App']['FetchNote'](arg1);
}

export function FetchNotes() {
  return window['go']['main']['App']['FetchNotes']();
}

export function FetchObjective(arg1) {
  return window['go']['main']['App']['FetchObjective'](arg1);
}

export function FetchObjectives() {
  return window['go']['main']['App']['FetchObjectives']();
}

export function FetchProject(arg1) {
  return window['go']['main']['App']['FetchProject'](arg1);
}

export function FetchProjects() {
  return window['go']['main']['App']['FetchProjects']();
}

export function FetchTask(arg1) {
  return window['go']['main']['App']['FetchTask'](arg1);
}

export function FetchTasks() {
  return window['go']['main']['App']['FetchTasks']();
}

export function MarkTaskAsCompleted(arg1) {
  return window['go']['main']['App']['MarkTaskAsCompleted'](arg1);
}

export function UpdateGoal(arg1) {
  return window['go']['main']['App']['UpdateGoal'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateObjective(arg1) {
  return window['go']['main']['App']['UpdateObjective'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
