// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateObjective(arg1) {
  return window['go']['main']['App']['CreateObjective'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteObjective(arg1) {
  return window['go']['main']['App']['DeleteObjective'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function FetchGoal(arg1) {
  return window['go']['main']['App']['FetchGoal'](arg1);
}

export function FetchGoals() {
  return window['go']['main']['App']['FetchGoals']();
}

export function FetchObjective(arg1) {
  return window['go']['main']['App']['FetchObjective'](arg1);
}

export function FetchObjectives() {
  return window['go']['main']['App']['FetchObjectives']();
}

export function FetchProject(arg1) {
  return window['go']['main']['App']['FetchProject'](arg1);
}

export function FetchProjects() {
  return window['go']['main']['App']['FetchProjects']();
}

export function UpdateGoal(arg1) {
  return window['go']['main']['App']['UpdateGoal'](arg1);
}

export function UpdateObjective(arg1) {
  return window['go']['main']['App']['UpdateObjective'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
