// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateProject(arg1:models.Project):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function FetchProject(arg1:number):Promise<models.Project>;

export function FetchProjects():Promise<Array<models.Project>>;

export function UpdateProject(arg1:models.ProjectUpdateDTO):Promise<void>;
